### ISSUE TITLE
Update the security configuration documentation

### ISSUE THREAD

**Issue by pradine** [cloudfoundry/ibm-websphere-liberty-buildpack#143]
The document, https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack/blob/master/docs/restrictions.md, describes security configuration based on the ssl-1.0 feature. This needs to be updated to reflect the latest recommendation, https://developer.ibm.com/answers/questions/16016/how-do-i-enforce-ssl-for-my-bluemix-application/

**Comment by jmarrero** [comment]
The documentation mentioned, is only for Bluemix, this buildpack works on Cloud Foundry clouds in general not only Bluemix.
