### ISSUE TITLE
Packaging offline buildpack fails behind a proxy

### ISSUE THREAD

**Issue by palonsoro** [cloudfoundry/ibm-websphere-liberty-buildpack#198]
Good evening.

I have recently tried to package the buildpack as an offline buildpack (via `bundle exec rake package OFFLINE=true`) and it fails to download dependencies to the cache. I must use an HTTP proxy, so I configured its URL on `$http_proxy` and `$https_proxy`environment variables (I have tried both uppercase and lowercase names). However, it does not work.
 
Examining traces, it looks like `rake` insists on downloading them without using the proxy. This is strange because [Net::HTTP](http://ruby-doc.org/stdlib-2.0.0/libdoc/net/http/rdoc/Net/HTTP.html) Ruby class seems to be used to perform the download and that class is supposed to take the aforementioned environment variables into account (as pointed by its documentation).

**Comment by jgawor** [comment]
This is resolved now as part of #238.
