### ISSUE TITLE
README references incorrect Liberty license

### ISSUE THREAD

**Issue by davidcurrie** [cloudfoundry/ibm-websphere-liberty-buildpack#234]
The top level readme references the license for Liberty 8.5.5.5 but the buildpack is now pulling 8.5.5.6 by default.

**Comment by jgawor** [comment]
Thanks. Fixed in https://github.com/jgawor/ibm-websphere-liberty-buildpack/commit/398d03077563aa1d3918d1765ae4e3c58c68958c.

**Comment by davidcurrie** [comment]
Thanks Jarek
