### ISSUE TITLE
Match Java buildpack customization capability for JRE

### ISSUE THREAD

**Issue by shouah** [cloudfoundry/ibm-websphere-liberty-buildpack#240]
The available documentation suggests the customization capability of the Java buildpack is not present for the IBM JRE or Open JRE as included here, specifically we are looking for the ability to add the unlimited JCE strength and custom CA certificates to the IBM JRE.

**Comment by jgawor** [comment]
That's already supported but not well documented on GitHub. We will need to fix that. Take a look at "Overlaying the JRE" on [Liberty for Java](https://www.ng.bluemix.net/docs/starters/liberty/index.html#customizingjre) documentation.
