### ISSUE TITLE
jrebel 6.4.2a prevents build

### ISSUE THREAD

**Issue by muthu-s** [cloudfoundry/ibm-websphere-liberty-buildpack#275]
Hi,

jrebel 6.4.2a prevents this buildpack build. I tried to disable the repository in jrebelagent.yml , but it doesnt work. Since the buildpack stores the cached yml in /tmp location. I am not able to remove the latest version as well.

rake aborted!
Invalid micro version '2a'
/tmp/ibm-websphere-liberty-buildpack/lib/liberty_buildpack/util/tokenized_version.rb:99:in `micro_and_qualifier'
/tmp/ibm-websphere-liberty-buildpack/lib/liberty_buildpack/util/tokenized_version.rb:38:in `initialize'
/tmp/ibm-websphere-liberty-buildpack/lib/liberty_buildpack/repository/version_resolver.rb:42:in `new'
/tmp/ibm-websphere-liberty-buildpack/lib/liberty_buildpack/repository/version_resolver.rb:42:in `block in resolve'
/tmp/ibm-websphere-liberty-buildpack/lib/liberty_buildpack/repository/version_resolver.rb:41:in `map'
/tmp/ibm-websphere-liberty-buildpack/lib/liberty_buildpack/repository/version_resolver.rb:41:in `resolve'
/tmp/ibm-websphere-liberty-buildpack/resources/download_buildpack_cache.rb:59:in `block in download_cache'
/tmp/ibm-websphere-liberty-buildpack/resources/download_buildpack_cache.rb:47:in `each'
/tmp/ibm-websphere-liberty-buildpack/resources/download_buildpack_cache.rb:47:in `download_cache'
/tmp/ibm-websphere-liberty-buildpack/Rakefile:95:in `block (2 levels) in <top (required)>'
/tmp/ibm-websphere-liberty-buildpack/Rakefile:78:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p545/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p545/bin/ruby_executable_hooks:15:in `<main>'

**Comment by jgawor** [comment]
This was fixed in #277.

**Comment by muthu-s** [comment]
thanks
