### ISSUE TITLE
{default.repository.root} variable in mongo.yml

### ISSUE THREAD

**Issue by mcelep** [cloudfoundry/ibm-websphere-liberty-buildpack#281]
Hi,

Using the _repository.root_ variable in mongo.yml throws an exception. It would be practical to use this variable in all configuration files.

config line: client_jar_url: ! '{default.repository.root}/mongodb/2.13.3/mongo-java-driver-2.13.3.jar'

Failing with:
```
Installing archive ... (1.0s)
E, 2016-04-17T14:51:14.849569 #14 ERROR – /tmp/buildpacks/5ff2ca7f7e3f4422b1d4e131cbc34544/lib/liberty_buildpack/buildpack.rb:50:in `rescue in drive_buildpack_with_logger': Compile failed with exception #<URI::InvalidURIError: bad URI(is not URI?
):
{default.repository.root}/mongodb/2.13.3/mongo-java-driver-2.13.3.jar>
bad URI(is not URI?): {default.repository.root}
/mongodb/2.13.3/mongo-java-driver-2.13.3.jar
Failed to compile droplet
-----> Retrieving and installing client jar(s) from mongo-java-driver-2.13.3.jar Exit status 223

```
Best regards,
Murat

**Comment by jgawor** [comment]
This should be addressed by https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack/commit/cf6b3ec41ede38c7727fa38f6d588b8695869e84.
