### ISSUE TITLE
Introscope agent support

### ISSUE THREAD

**Issue by dhrapson** [cloudfoundry/ibm-websphere-liberty-buildpack#293]
The Java Buildpack (https://github.com/cloudfoundry/java-buildpack) has CA Introscope support.  I'm consulting at a company that would like to use Introscope with the IBM WAS Liberty Buildpack.

 The java-buildpack can download and configure the introscope agent, however it is not configured with any URL from which to download the tar file containing the agent code.

We have been considering forking the liberty buildpack in order to copy over support for CA Introscope agent deployment, and add it into this repository. If we did that, and we created a PR, would it likely be accepted?

**Comment by jgawor** [comment]
Assuming you sign the necessary CLA (you'll see info about that as soon as you submit a PR), provide tests, and work with us on addressing any code issues, etc. I don't see why we wouldn't accept it.

Btw, the URL for the agent in the Java buildpack can be set using an environment property.

**Comment by dhrapson** [comment]
OK - got that. Thanks
