### ISSUE TITLE
deploy to Bluemix fails (dallas-ys1-dev)

### ISSUE THREAD

**Issue by srigithub2** [cloudfoundry/ibm-websphere-liberty-buildpack#298]
/var/vcap/data/dea_next/admin_buildpacks/835c0bc0-b348-483e-b6b7-fba1a13b5eee_81ed6c377b313491ee3656bb8eae39b3ad8a74cf/lib/liberty_buildpack/buildpack.rb:50:in `rescue in drive_buildpack_with_logger': Compile failed with exception #<RuntimeError: No supported application type was detected>

the artifactory location is bmd-libs-snapshot-local/bluemix-mobile-services/bms-mqa/bms-mqa-56dce57d5fc821698f229cd7c009095e9dc810f6.zip 
The zip contains a .war and other files.

**Comment by jgawor** [comment]
Is there more to the error? How is the zip file structured? It has to be a Liberty packaged server or a sever directory for the Liberty buildpack to recognize it.

**Comment by srigithub2** [comment]
Issue is not relevant anymore. Pl close it. 

Get Outlook for iOS




On Wed, Sep 7, 2016 at 3:04 PM -0400, "Jarek Gawor" <notifications@github.com> wrote:












Is there more to the error? How is the zip file structured? It has to be a Liberty packaged server or a sever directory for the Liberty buildpack to recognize it.
