### ISSUE TITLE
Proper autowiring for PostgreSQL database JDBC

### ISSUE THREAD

**Issue by romankhar** [cloudfoundry/ibm-websphere-liberty-buildpack#305]
When deploying Liberty packaged server into Bluemix and using ElephantSQL (PostgreSQL) JDBC the autowiring updates database connection properties, but fails to find proper JDBC driver in the library. See this post for more details: http://stackoverflow.com/questions/39370482/cant-find-valid-jdbc-driver-when-deploying-liberty-app-in-bluemix-with-elephant

**Comment by jmarrero** [comment]
Thanks for reporting the issue, I will investigate further.

**Comment by jmarrero** [comment]
Trying to address this issue in my branch:
https://github.com/jmarrero/ibm-websphere-liberty-buildpack/tree/update-datasource

with the commit:
https://github.com/jmarrero/ibm-websphere-liberty-buildpack/commit/04f78d07fe61ed4a3378698b141fb16cae2a7e9f

Still testing, will update this issue again soon.

**Comment by jmarrero** [comment]
New code on the commit: https://github.com/jmarrero/ibm-websphere-liberty-buildpack/commit/31a4dcc82d30244bc449a88d5a89344ff36028e7
connects to the database, seems to be working, performing additional tests.
