### ISSUE TITLE
Accessing the Information of Bound Services in server-xml-options.md is outdated

### ISSUE THREAD

**Issue by tobilarscheid** [cloudfoundry/ibm-websphere-liberty-buildpack#322]
The link pointing to the Cloud Foundry service variable specification (http://docs.cloudfoundry.com/docs/using/services/spring-service-bindings.html#properties) is outdated. Cloud Foundry is redirecting to a generic deprecation notice.

**Comment by jgawor** [comment]
Thanks. Fixed in https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack/commit/a2466a8a6f0429946a6ef231757648eea3d96c36.
