### ISSUE TITLE
auto-configuration with postgresql

### ISSUE THREAD

**Issue by franktao2008** [cloudfoundry/ibm-websphere-liberty-buildpack#336]
A Java JPA application connect to a "compose for postgresql" database using auto-configuration. 

The databaseName of the datasource in server.xml is generated, e.g. databaseName="${cloud.services.postgresqlDB.connection.name}", but the variable is binding to "VCAP_SERVICES.compose-for-postgresql.creadientials.name" in runtime-vars.xml, which is "bmix_dal_yp_14f08adb_....". **This is not the name of the database.**

<variable name='cloud.services.postgresqlDB.connection.name' value='bmix_dal_yp_14f08adb_....

The JPA application can't connect to the postgressql database. 
The error message is "java.sql.SQLException: FATAL: database "bmix_dal_yp_14f08adb_*** does not exist DSRA0010E: SQL State = 3D000, Error Code = 0." 

P.S. it works fine if the databaseName is configured manually.

**Comment by jmarrero** [comment]
This has been addressed on Pull Request #333
