### ISSUE TITLE
Add no_proxy variable functionality 

### ISSUE THREAD

**Issue by saloiyh1** [cloudfoundry/ibm-websphere-liberty-buildpack#337]
Currently, if an http_proxy or https_proxy is set the liberty buildpack will always use these proxies.   Typically, you can add IP addresses to the no_proxy variable to selectively chose which IP addresses should not use a proxy.  However, the buildpack does not currently recognize this variable.   

Can you implement honoring this variable?

**Comment by opiethehokie** [comment]
Can you elaborate on your use case a bit more? I'm not sure I understand why this would be needed.

**Comment by saloiyh1** [comment]
@opiethehokie Here is our use case:
Right now, if our team sets the http_proxy or https_proxy, this applies the the buildpack globally.  This is causing an issue when there are resources in private (internal to our company) repositories which reside on servers that are configured not to use a proxy.  The Java buildpack has a no_proxy variable to address cases such as these, but the Liberty Buildpack does not.  We are asking this functionality to keep our resources (e.g. binary files, configuration files etc.) in our internal server, and also access resources located on servers which do require a proxy to be set.

**Comment by tomaszkosturekswissre** [comment]
Definitely a +1 to this request. Why force internal traffic to go via the proxy.

**Comment by ptamma** [comment]
On the mainstream Java Buildpack this has been fixed with 3.18 release . https://github.com/cloudfoundry/java-buildpack/issues/438

@opiethehokie is the issue considered ?. The fix will support on premises private CF deployment.

**Comment by opiethehokie** [comment]
@ptamma I agree it would be useful but don't have time to work on it right now. A pull request would be welcome, or I'll get to it as soon as possible.
