### ISSUE TITLE
Configs to push all logs to stdout/stderr for pickup by loggregator

### ISSUE THREAD

**Issue by dougmcclure** [cloudfoundry/ibm-websphere-liberty-buildpack#34]
What configuration changes are required so that Liberty will send all of its logs (SystemOut, SystemErr, trace, etc.) to stdout/stderr so they can be routed out of CF environment using loggregator?

Where would configuration changes be made to increase the logging levels?

Tks!

**Comment by jmarrero** [comment]
There is no plan to implement this.

**Comment by lmsurpre** [comment]
perhaps a little different than what the asker wanted, but I think it's worth mentioning that you can redirect liberty message/trace log messages to stdout by setting 
`com.ibm.ws.logging .trace.file.name=stdout` in a file called bootstrap.properties and putting that alongside your server.xml

source: https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_logging.html
