### ISSUE TITLE
ibmjdk heapsize handling bug

### ISSUE THREAD

**Issue by tomaszkosturekswissre** [cloudfoundry/ibm-websphere-liberty-buildpack#340]
There seems to be a bug handling memory settings under 1024MB when applying the heap_size_ratio.

Whenever I set the memory for the application to less than 1024M, the buildpack sets the -Xmx property in jvm.options to 1024M * heap_size_ratio. This basically means that whatever memory I try to set (500M, 600M, 800M) it always sets -Xmx768M (1024*0.75). I have tested this by changing the heap_size_ratio and when I set to 1 it always sets -Xmx1024M regardless of the memory I set to the application container.

Everything works as expected for memory settings above 1024M.

**Comment by opiethehokie** [comment]
I just pushed an app with 512M and my jvm.options has -Xmx384M as expected.

**Comment by tomaszkosturekswissre** [comment]
Perhaps it's related to version 2.4.0.0. I will try to upgrade.

**Comment by mcelep** [comment]
The following text from [CF Doc](https://docs.cloudfoundry.org/concepts/how-applications-are-staged.html)

>Apps are given a minimum of 1GB memory to stage, even if the requested running memory is smaller.


might explain the behavior observed by @tomaszkosturekswissre . When I ssh into the container of an app with memory less than 1GB, I see that MEMORY_LIMIT environment value is set correctly. The debug message(by liberty_buildpack/buildpack.rb:194) that is generated during staging phase however still includes:  _"MEMORY_LIMIT"=>"1024m"_

So I'm curious how come it works for you @opiethehokie . Which version of the buildpack are you running and what version of Diego?

**Comment by opiethehokie** [comment]
@mcelep master branch of buildpack and Diego v0.1487, so maybe there is a change in a newer Diego causing the difference.

**Comment by jgawor** [comment]
Right now, you'll need to *restage* (instead of the *restart*) the application, for the memory settings to pick up correctly in the Liberty buildpack. Alternatively, you can override the memory settings via the `JVM_ARGS` environment variables that works just with restarts.

**Comment by tomaszkosturekswissre** [comment]
I don't have this problem in any update (restage/restart) scenario, but already in the initial application staging when I push an application with less than 1024M memory.

**Comment by jmarrero** [comment]
@tomaszkosturekswissre We are investigating the issue and a possible way to change the way we handle the memory calculations. Will maintain the the issue updated with our progress.

**Comment by opiethehokie** [comment]
To follow up on this ... it appears that the staging MEMORY_LIMIT change happened in CF v245 and not in a particular Diego version. Apps running on the DEA are unaffected, apps running on Diego are affected though.

**Comment by tomaszkosturekswissre** [comment]
@opiethehokie I assume the fix did not make its way into 2.7?

**Comment by opiethehokie** [comment]
@tomaszkosturekswissre you are correct, nothing in 2.7 for this problem.

**Comment by opiethehokie** [comment]
For reference, there is more information about the CF change that caused this problem in https://github.com/cloudfoundry/cloud_controller_ng/issues/782.

**Comment by jmarrero** [comment]
@tomaszkosturekswissre we have just merged a change to address this for the IBM JDK, a similar fix for the openjdk is under development. Would you confirm that the recently merged code fixes your issue with the IBM JDK?

**Comment by jmarrero** [comment]
closing as it has been addressed by #350 and #351
