### ISSUE TITLE
Jndi Binding MongoDB 3.2.9 to Liberty applications Failed (CWKKD0013E & CWNEN0074E)

### ISSUE THREAD

**Issue by DominiqueBertrand** [cloudfoundry/ibm-websphere-liberty-buildpack#341]
I using the Liberty feature mongodb-2.0 

The jndi binding failed for the both mongo-java-driver versions below:

1/ mongo-java-driver 3.2.2. 
CWKKD0013E: The mongo service encountered an unsupported version of the MongoDB driver at shared library mongo-lib. Expected a minimum level of 2.10, **but found -1.-1.**

2/ mongo-java-driver 2.14.2
javax.ejb.EJBException: CWNEN0074E: The com.mongodb.DBApiLayer type of the object instance obtained for the java:comp/env/mongo/myDB reference is incompatible with the type of the com.mongodb.DB com.sample.ejb.impl.MyManagerBean.mongoDB member.; nested exception is: java.lang.IllegalArgumentException: Can not set com.mongodb.DB field com.sample.ejb.impl.MyManagerBean.mongoDB to com.mongodb.DBApiLayer com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters 1105

**Comment by opiethehokie** [comment]
According to https://www.ibm.com/support/knowledgecenter/SSEQTP_8.5.5/com.ibm.websphere.wlp.doc/ae/twlp_mongodb_create.html only MongoDB Java driver versions 2.10.0 to 2.12.5 are supported by Liberty.

**Comment by DominiqueBertrand** [comment]
I understand but according to https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#id7 only MongoDB Java driver versions 2.14+ are compatible with MongoDB 3.2.

When do you plan to support MongoDB 3.2 ?

**Comment by opiethehokie** [comment]
Unfortunately I can't comment on future Liberty plans here. Closing this since it is a problem with the Liberty server and not the buildpack.
