### ISSUE TITLE
Cannot exclude Cloudant service from auto-configuring in Liberty

### ISSUE THREAD

**Issue by yourlearning** [cloudfoundry/ibm-websphere-liberty-buildpack#349]
When we bind any Cloudant instance in dedicated Bluemx, it tries to auto-configure it in Liberty during staging:
`
-----> Auto-configuration is updating config for service instance 'ChannelsDEV' of type 'cloudantNoSQLDB'
`
Per the documentation, it can be excluded by using `services_autoconfig_excluded` environmental variables - https://console.ng.bluemix.net/docs/runtimes/liberty/autoConfig.html#opting_out
_Important: The service type that you specify must match the services label as it appears in the VCAP_SERVICES environment variable. White space is not allowed. Important: No white space is allowed within a <service_type_specification>._

Problem is that label for Cloudant services in our Dedicated Bluemix is `cloudantNoSQLDB Dedicated`, it means there is space. 

Following snippet:
```
  env:
    services_autoconfig_excludes: cloudantNoSQLDB Dedicated=all
```
is invalid and doesn't allow white space there. We cannot change the label of service.

**Comment by jmarrero** [comment]
services_autoconfig_excludes: cloudantNoSQLDB=all

does not work for you either?

service_type_specification should not look at your service name but the type, which should match cloudantNoSQLDB.

**Comment by jmarrero** [comment]
Also try:

```
env:
    services_autoconfig_excludes: cloudantNoSQLDB-Dedicated=all
```

If the above recommendations do not work please let us know.

**Comment by opiethehokie** [comment]
I think the above recommendations should work, if not please reopen.
