### ISSUE TITLE
How license work in no network environment 

### ISSUE THREAD

**Issue by youflint** [cloudfoundry/ibm-websphere-liberty-buildpack#353]
hi,
My cloudfoundry runs in a no network environment, and when I compile throws error.
I thought the IBM_JVM_LICENSE and IBM_LIberty_LICENSE (using https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/17.0.0.1/lafiles/runtime/en.html)
can not grant in no network environment
how can I grant license in this requirement,do buy a formal license work?

**Comment by jmarrero** [comment]
Hi @youflint you have a local repository with Liberty 17.0.0.1 and the JDK? If so make sure that the license versions match the Liberty versions. If you don't have a local repository with Liberty or the JDK. Then the buildpack will not work for you. The Liberty runtime and JDK are downloaded using a internet connection they are not cached in the buildpack.

**Comment by jeffwdg** [comment]
Ive used the java and liberty license and the command still doesnt work for me.
cf push <APP-NAME> -p <ARCHIVE> -b https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack.git

**Comment by jmarrero** [comment]
You need a network connection to be able to download Liberty and the JDK. Unless you have a local repository with the files, adding the licenses would not help in your case. Also make sure you provide a path to your application when you specify the -p option.
