### ISSUE TITLE
Unable to create an admin Buildpack

### ISSUE THREAD

**Issue by bpogace** [cloudfoundry/ibm-websphere-liberty-buildpack#373]
Trying to create an admin Buildpack with just a slight modification. After executing ` bundle exec rake package ` this is the last part of the log: 
`D, [2018-01-25T17:39:03.265589 #17892] DEBUG -- C:/Users/bpogace/ibm-websphere-liberty-buildpack/resources/download_buildpack_cache.rb:121:in 'proxy': Proxy: , , ,
FIND: Parameter format not correct
FIND: Parameter format not correct
File not found - '*.bin.cached'
  adding: admin_cache/ (stored 0%)
  adding: admin_cache/http%3A%2F%2Fdownloads.dynatracesaas.com%2Fcloudfoundry%2Fbuildpack%2Fjava%2Findex.yml.cached (deflated 39%)
  adding: admin_cache/http%3A%2F%2Ffiles.dynatrace.com%2Fdownloads%2FOnPrem%2FdynaTrace%2F6.5%2F6.5.0.1289%2Fdynatrace-agent-6.5.0.1289-unix.jar.cached (deflated 2%)
  adding: admin_cache/https%3A%2F%2Fdl.zeroturnaround.com%2Fjrebel%2Findex.yml.cached (deflated 91%)
  adding: admin_cache/https%3A%2F%2Fdl.zeroturnaround.com%2Fjrebel%2Freleases%2Fjrebel-7.1.5-nosetup.zip.cached (deflated 0%)
  adding: admin_cache/https%3A%2F%2Fdownload.run.pivotal.io%2Fapp-dynamics%2Findex.yml.cached (deflated 93%)
  adding: admin_cache/https%3A%2F%2Fdownload.run.pivotal.io%2Fauto-reconfiguration%2Findex.yml.cached (deflated 92%)
  adding: admin_cache/https%3A%2F%2Fdownload.run.pivotal.io%2Fmariadb-jdbc%2Findex.yml.cached (deflated 91%)
  adding: admin_cache/https%3A%2F%2Fdownload.run.pivotal.io%2Fnew-relic%2Findex.yml.cached (deflated 92%)
  adding: admin_cache/https%3A%2F%2Fdownload.run.pivotal.io%2Fnew-relic%2Fnew-relic-3.46.0.jar.cached (deflated 10%)
  adding: admin_cache/https%3A%2F%2Fdownload.run.pivotal.io%2Fopenjdk%2Ftrusty%2Fx86_64%2Findex.yml.cached (deflated 92%)
  adding: admin_cache/https%3A%2F%2Fdownload.run.pivotal.io%2Fpostgresql-jdbc%2Findex.yml.cached (deflated 91%)
  adding: admin_cache/https%3A%2F%2Fdownload.ruxit.com%2Fagent%2Fpaas%2Fcloudfoundry%2Fjava%2Findex.yml.cached (deflated 83%)
  adding: admin_cache/https%3A%2F%2Fdownload.ruxit.com%2Fagent%2Fpaas%2FDynatrace-OneAgent-linux-java-1.131.143.20171117-121745.zip.cached (deflated 0%)
  adding: admin_cache/https%3A%2F%2Fjava-buildpack.cloudfoundry.org%2Fapp-dynamics%2Fapp-dynamics-4.2.7_1.zip.cached (deflated 0%)
  adding: admin_cache/https%3A%2F%2Fjava-buildpack.cloudfoundry.org%2Fauto-reconfiguration%2Fauto-reconfiguration-1.12.0_RELEASE.jar.cached (deflated 17%)
  adding: admin_cache/https%3A%2F%2Fjava-buildpack.cloudfoundry.org%2Fmariadb-jdbc%2Fmariadb-jdbc-1.5.9.jar.cached (deflated 7%)
  adding: admin_cache/https%3A%2F%2Fjava-buildpack.cloudfoundry.org%2Fopenjdk%2Ftrusty%2Fx86_64%2Fopenjdk-1.8.0_91-unlimited-crypto.tar.gz.cached (deflated 1%)
  adding: admin_cache/https%3A%2F%2Fjava-buildpack.cloudfoundry.org%2Fpostgresql-jdbc%2Fpostgresql-jdbc-9.4.1212.jar.cached (deflated 5%)
  adding: admin_cache/https%3A%2F%2Fpublic.dhe.ibm.com%2Fibmdl%2Fexport%2Fpub%2Fsoftware%2Fwebsphere%2Fwasdev%2Fdownloads%2Fwlp%2F17.0.0.4%2Flafiles%2Fruntime%2Fen.html.cached (deflated 70%)
  adding: admin_cache/https%3A%2F%2Fpublic.dhe.ibm.com%2Fibmdl%2Fexport%2Fpub%2Fsoftware%2Fwebsphere%2Fwasdev%2Fdownloads%2Fwlp%2F17.0.0.4%2Fwlp-webProfile7-17.0.0.4.zip.cached (deflated 0%)
  adding: admin_cache/https%3A%2F%2Fpublic.dhe.ibm.com%2Fibmdl%2Fexport%2Fpub%2Fsoftware%2Fwebsphere%2Fwasdev%2Fdownloads%2Fwlp%2Findex.yml.cached (deflated 89%)
  adding: admin_cache/https%3A%2F%2Fpublic.dhe.ibm.com%2Fibmdl%2Fexport%2Fpub%2Fsystems%2Fcloud%2Fruntimes%2Fjava%2Fmeta%2Fjre%2Flinux%2Fx86_64%2Findex.yml.cached (deflated 81%)
  adding: bin/ (stored 0%)
  adding: bin/compile (deflated 40%)
  adding: bin/detect (deflated 39%)
  adding: bin/release (deflated 39%)
  adding: config/ (stored 0%)
  adding: config/appdynamicsagent.yml (deflated 40%)
  adding: config/cache.yml (deflated 38%)
  adding: config/components.yml (deflated 58%)
  adding: config/containercertificatetruststore.yml (deflated 40%)
  adding: config/dynatraceappmonagent.yml (deflated 38%)
  adding: config/dynatraceoneagent.yml (deflated 37%)
  adding: config/env.yml (deflated 37%)
  adding: config/ibmjdk.yml (deflated 37%)
  adding: config/javaopts.yml (deflated 37%)
  adding: config/jrebelagent.yml (deflated 38%)
  adding: config/liberty.yml (deflated 46%)
  adding: config/licenses.yml (deflated 17%)
  adding: config/logging.yml (deflated 38%)
  adding: config/newrelicagent.yml (deflated 37%)
  adding: config/openjdk.yml (deflated 43%)
  adding: config/repository.yml (deflated 38%)
  adding: config/springautoreconfiguration.yml (deflated 42%)
  adding: config/version.yml (deflated 7%)
  adding: CONTRIBUTING.md (deflated 57%)
  adding: doc/ (stored 0%)
  adding: doc/class_list.html (deflated 91%)
  adding: doc/css/ (stored 0%)
  adding: doc/css/common.css (stored 0%)
  adding: doc/css/full_list.css (deflated 50%)
  adding: doc/css/style.css (deflated 63%)
  adding: doc/file.LICENSE.html (deflated 64%)
  adding: doc/file.NOTICE.html (deflated 62%)
  adding: doc/file.README.html (deflated 65%)
  adding: doc/file_list.html (deflated 69%)
  adding: doc/frames.html (deflated 37%)
  adding: doc/index.html (deflated 65%)
  adding: doc/js/ (stored 0%)
  adding: doc/js/app.js (deflated 70%)
  adding: doc/js/full_list.js (deflated 66%)
  adding: doc/js/jquery.js (deflated 65%)
  adding: doc/LibertyBuildpack/ (stored 0%)
  adding: doc/LibertyBuildpack/Buildpack.html (deflated 84%)
  adding: doc/LibertyBuildpack/BuildpackVersion.html (deflated 85%)
  adding: doc/LibertyBuildpack/Container/ (stored 0%)
  adding: doc/LibertyBuildpack/Container/CommonPaths.html (deflated 81%)
  adding: doc/LibertyBuildpack/Container/ContainerUtils.html (deflated 87%)
  adding: doc/LibertyBuildpack/Container/DistZip.html (deflated 86%)
  adding: doc/LibertyBuildpack/Container/FeatureManager.html (deflated 85%)
  adding: doc/LibertyBuildpack/Container/InstallComponents.html (deflated 81%)
  adding: doc/LibertyBuildpack/Container/JavaMain.html (deflated 81%)
  adding: doc/LibertyBuildpack/Container/Liberty.html (deflated 85%)
  adding: doc/LibertyBuildpack/Container/OptionalComponents.html (deflated 75%)
  adding: doc/LibertyBuildpack/Container/ServicesManager.html (deflated 88%)
  adding: doc/LibertyBuildpack/Container/WebXmlExt.html (deflated 80%)
  adding: doc/LibertyBuildpack/Container.html (deflated 70%)
  adding: doc/LibertyBuildpack/Diagnostics/ (stored 0%)
  adding: doc/LibertyBuildpack/Diagnostics/LoggerFactory/ (stored 0%)
  adding: doc/LibertyBuildpack/Diagnostics/LoggerFactory/Logger.html (deflated 79%)
  adding: doc/LibertyBuildpack/Diagnostics/LoggerFactory/LogSplitter.html (deflated 78%)
  adding: doc/LibertyBuildpack/Diagnostics/LoggerFactory.html (deflated 80%)
  adding: doc/LibertyBuildpack/Diagnostics.html (deflated 79%)
  adding: doc/LibertyBuildpack/Framework/ (stored 0%)
  adding: doc/LibertyBuildpack/Framework/AppDynamicsAgent.html (deflated 83%)
  adding: doc/LibertyBuildpack/Framework/ContainerCertificateTrustStore.html (deflated 80%)
  adding: doc/LibertyBuildpack/Framework/DynamicPULSEAgent.html (deflated 84%)
  adding: doc/LibertyBuildpack/Framework/DynatraceAppmonAgent.html (deflated 83%)
  adding: doc/LibertyBuildpack/Framework/DynatraceOneAgent.html (deflated 84%)
  adding: doc/LibertyBuildpack/Framework/Env.html (deflated 83%)
  adding: doc/LibertyBuildpack/Framework/FrameworkUtils.html (deflated 90%)
  adding: doc/LibertyBuildpack/Framework/JavaOpts.html (deflated 79%)
  adding: doc/LibertyBuildpack/Framework/JRebelAgent.html (deflated 84%)
  adding: doc/LibertyBuildpack/Framework/NewRelicAgent.html (deflated 83%)
  adding: doc/LibertyBuildpack/Framework/SpringAutoReconfiguration.html (deflated 81%)
  adding: doc/LibertyBuildpack/Framework/WebXmlModifier.html (deflated 80%)
  adding: doc/LibertyBuildpack/Framework.html (deflated 74%)
  adding: doc/LibertyBuildpack/Jre/ (stored 0%)
  adding: doc/LibertyBuildpack/Jre/IBMJdk.html (deflated 82%)
  adding: doc/LibertyBuildpack/Jre/OpenJdk.html (deflated 82%)
  adding: doc/LibertyBuildpack/Jre.html (deflated 63%)
  adding: doc/LibertyBuildpack/Repository/ (stored 0%)
  adding: doc/LibertyBuildpack/Repository/ComponentIndex.html (deflated 75%)
  adding: doc/LibertyBuildpack/Repository/ConfiguredItem.html (deflated 78%)
  adding: doc/LibertyBuildpack/Repository/RepositoryIndex.html (deflated 79%)
  adding: doc/LibertyBuildpack/Repository/RepositoryUtils.html (deflated 79%)
  adding: doc/LibertyBuildpack/Repository/VersionResolver.html (deflated 74%)
  adding: doc/LibertyBuildpack/Repository.html (deflated 69%)
  adding: doc/LibertyBuildpack/Services/ (stored 0%)
  adding: doc/LibertyBuildpack/Services/ClientJarUtils.html (deflated 87%)
  adding: doc/LibertyBuildpack/Services/ComposeMongo.html (deflated 87%)
  adding: doc/LibertyBuildpack/Services/ComposeMySQL.html (deflated 84%)
  adding: doc/LibertyBuildpack/Services/ComposePostgreSQL.html (deflated 84%)
  adding: doc/LibertyBuildpack/Services/Default.html (deflated 85%)
  adding: doc/LibertyBuildpack/Services/Mongo.html (deflated 90%)
  adding: doc/LibertyBuildpack/Services/MySQL.html (deflated 84%)
  adding: doc/LibertyBuildpack/Services/PostgreSQL.html (deflated 83%)
  adding: doc/LibertyBuildpack/Services/RelationalDatabasePlugin.html (deflated 89%)
  adding: doc/LibertyBuildpack/Services/Utils.html (deflated 89%)
  adding: doc/LibertyBuildpack/Services/VcapServices.html (deflated 81%)
  adding: doc/LibertyBuildpack/Services.html (deflated 73%)
  adding: doc/LibertyBuildpack/Util/ (stored 0%)
  adding: doc/LibertyBuildpack/Util/Cache/ (stored 0%)
  adding: doc/LibertyBuildpack/Util/Cache/AdminCache.html (deflated 73%)
  adding: doc/LibertyBuildpack/Util/Cache/ApplicationCache.html (deflated 73%)
  adding: doc/LibertyBuildpack/Util/Cache/AuthenticationUtils.html (deflated 75%)
  adding: doc/LibertyBuildpack/Util/Cache/CachedFile.html (deflated 87%)
  adding: doc/LibertyBuildpack/Util/Cache/DownloadCache.html (deflated 80%)
  adding: doc/LibertyBuildpack/Util/Cache/InferredNetworkFailure.html (deflated 66%)
  adding: doc/LibertyBuildpack/Util/Cache/InternetAvailability.html (deflated 79%)
  adding: doc/LibertyBuildpack/Util/Cache.html (deflated 71%)
  adding: doc/LibertyBuildpack/Util/ConfigurationUtils.html (deflated 82%)
  adding: doc/LibertyBuildpack/Util/Heroku.html (deflated 84%)
  adding: doc/LibertyBuildpack/Util/JavaMainUtils.html (deflated 79%)
  adding: doc/LibertyBuildpack/Util/LocationResolver.html (deflated 84%)
  adding: doc/LibertyBuildpack/Util/Properties.html (deflated 74%)
  adding: doc/LibertyBuildpack/Util/ServiceConfigurationUtils.html (deflated 80%)
  adding: doc/LibertyBuildpack/Util/TokenizedVersion.html (deflated 80%)
  adding: doc/LibertyBuildpack/Util/XmlUtils.html (deflated 81%)
  adding: doc/LibertyBuildpack/Util.html (deflated 88%)
  adding: doc/LibertyBuildpack.html (deflated 68%)
  adding: doc/method_list.html (deflated 93%)
  adding: doc/NilClass.html (deflated 65%)
  adding: doc/Numeric.html (deflated 77%)
  adding: doc/String.html (deflated 82%)
  adding: doc/top-level-namespace.html (deflated 64%)
  adding: doc/_index.html (deflated 91%)
  adding: docs/ (stored 0%)
  adding: docs/bootstrap-properties.md (deflated 47%)
  adding: docs/configuration/ (stored 0%)
  adding: docs/configuration/manifest.yml (deflated 22%)
  adding: docs/configuration.md (deflated 50%)
  adding: docs/container-distZip.md (deflated 52%)
  adding: docs/container-liberty.md (deflated 63%)
  adding: docs/design.md (deflated 64%)
  adding: docs/env.md (deflated 44%)
  adding: docs/extending-containers.md (deflated 61%)
  adding: docs/extending-frameworks.md (deflated 60%)
  adding: docs/extending-jres.md (deflated 58%)
  adding: docs/forking.md (deflated 51%)
  adding: docs/framework-app_dynamics_agent.md (deflated 63%)
  adding: docs/framework-container_certificate_trust_store.md (deflated 56%)
  adding: docs/framework-dynamic_pulse_agent.md (deflated 51%)
  adding: docs/framework-dynatrace_appmon_agent.md (deflated 58%)
  adding: docs/framework-dynatrace_one_agent.md (deflated 58%)
  adding: docs/framework-java_opts.md (deflated 51%)
  adding: docs/framework-jrebel-agent.md (deflated 54%)
  adding: docs/framework-new-relic-agent.md (deflated 57%)
  adding: docs/framework-spring-auto-reconfiguration.md (deflated 60%)
  adding: docs/heroku.md (deflated 68%)
  adding: docs/ibm-jdk.md (deflated 53%)
  adding: docs/installation.md (deflated 64%)
  adding: docs/java-main.md (deflated 48%)
  adding: docs/logging.md (deflated 55%)
  adding: docs/open-jdk.md (deflated 66%)
  adding: docs/restrictions.md (deflated 55%)
  adding: docs/security.md (deflated 41%)
  adding: docs/server-xml-options.md (deflated 66%)
  adding: docs/service-plugins.md (deflated 65%)
  adding: docs/services/ (stored 0%)
  adding: docs/services/mongo.md (deflated 67%)
  adding: docs/services/mysql.md (deflated 67%)
  adding: docs/services/postgresql.md (deflated 67%)
  adding: docs/troubleshooting.md (deflated 44%)
  adding: docs/tuning.md (deflated 54%)
  adding: docs/util-caches.md (deflated 59%)
  adding: docs/util-repositories.md (deflated 62%)
  adding: docs/util-repository-builder.md (deflated 34%)
  adding: docs/util-test-applications.md (deflated 42%)
  adding: Gemfile (deflated 46%)
  adding: Gemfile.lock (deflated 62%)
  adding: ibm-websphere-liberty-buildpack.iml (deflated 34%)
  adding: lib/ (stored 0%)
  adding: lib/liberty_buildpack/ (stored 0%)
  adding: lib/liberty_buildpack/buildpack.rb (deflated 68%)
  adding: lib/liberty_buildpack/buildpack_version.rb (deflated 63%)
  adding: lib/liberty_buildpack/container/ (stored 0%)
  adding: lib/liberty_buildpack/container/common_paths.rb (deflated 66%)
  adding: lib/liberty_buildpack/container/container_utils.rb (deflated 62%)
  adding: lib/liberty_buildpack/container/dist_zip.rb (deflated 66%)
  adding: lib/liberty_buildpack/container/feature_manager.rb (deflated 69%)
  adding: lib/liberty_buildpack/container/install_components.rb (deflated 62%)
  adding: lib/liberty_buildpack/container/java_main.rb (deflated 60%)
  adding: lib/liberty_buildpack/container/liberty.rb (deflated 75%)
  adding: lib/liberty_buildpack/container/optional_components.rb (deflated 60%)
  adding: lib/liberty_buildpack/container/services_manager.rb (deflated 74%)
  adding: lib/liberty_buildpack/container/web_xml_ext.rb (deflated 52%)
  adding: lib/liberty_buildpack/container.rb (deflated 40%)
  adding: lib/liberty_buildpack/diagnostics/ (stored 0%)
  adding: lib/liberty_buildpack/diagnostics/common.rb (deflated 56%)
  adding: lib/liberty_buildpack/diagnostics/logger_factory.rb (deflated 67%)
  adding: lib/liberty_buildpack/diagnostics.rb (deflated 40%)
  adding: lib/liberty_buildpack/framework/ (stored 0%)
  adding: lib/liberty_buildpack/framework/appdynamics_agent.rb (deflated 75%)
  adding: lib/liberty_buildpack/framework/container_certificate_trust_store.rb (deflated 65%)
  adding: lib/liberty_buildpack/framework/dynamic_pulse_agent.rb (deflated 60%)
  adding: lib/liberty_buildpack/framework/dynatrace_appmon_agent.rb (deflated 74%)
  adding: lib/liberty_buildpack/framework/dynatrace_one_agent.rb (deflated 74%)
  adding: lib/liberty_buildpack/framework/env.rb (deflated 60%)
  adding: lib/liberty_buildpack/framework/framework_utils.rb (deflated 68%)
  adding: lib/liberty_buildpack/framework/java_opts.rb (deflated 59%)
  adding: lib/liberty_buildpack/framework/jrebel_agent.rb (deflated 66%)
  adding: lib/liberty_buildpack/framework/new_relic_agent.rb (deflated 74%)
  adding: lib/liberty_buildpack/framework/spring_auto_reconfiguration/ (stored 0%)
  adding: lib/liberty_buildpack/framework/spring_auto_reconfiguration/web_xml_modifier.rb (deflated 64%)
  adding: lib/liberty_buildpack/framework/spring_auto_reconfiguration.rb (deflated 64%)
  adding: lib/liberty_buildpack/framework.rb (deflated 40%)
  adding: lib/liberty_buildpack/jre/ (stored 0%)
  adding: lib/liberty_buildpack/jre/ibmjdk.rb (deflated 63%)
  adding: lib/liberty_buildpack/jre/openjdk.rb (deflated 63%)
  adding: lib/liberty_buildpack/jre.rb (deflated 40%)
  adding: lib/liberty_buildpack/repository/ (stored 0%)
  adding: lib/liberty_buildpack/repository/component_index.rb (deflated 54%)
  adding: lib/liberty_buildpack/repository/configured_item.rb (deflated 61%)
  adding: lib/liberty_buildpack/repository/repository_index.rb (deflated 57%)
  adding: lib/liberty_buildpack/repository/repository_utils.rb (deflated 55%)
  adding: lib/liberty_buildpack/repository/version_resolver.rb (deflated 62%)
  adding: lib/liberty_buildpack/repository.rb (deflated 40%)
  adding: lib/liberty_buildpack/services/ (stored 0%)
  adding: lib/liberty_buildpack/services/client_jar_utils.rb (deflated 73%)
  adding: lib/liberty_buildpack/services/compose_mongo.rb (deflated 76%)
  adding: lib/liberty_buildpack/services/compose_mysql.rb (deflated 62%)
  adding: lib/liberty_buildpack/services/compose_postgresql.rb (deflated 63%)
  adding: lib/liberty_buildpack/services/config/ (stored 0%)
  adding: lib/liberty_buildpack/services/config/compose_mongo.yml (deflated 42%)
  adding: lib/liberty_buildpack/services/config/compose_mysql.yml (deflated 41%)
  adding: lib/liberty_buildpack/services/config/compose_postgresql.yml (deflated 42%)
  adding: lib/liberty_buildpack/services/config/default.yml (deflated 47%)
  adding: lib/liberty_buildpack/services/config/mongo.yml (deflated 41%)
  adding: lib/liberty_buildpack/services/config/mysql.yml (deflated 41%)
  adding: lib/liberty_buildpack/services/config/postgresql.yml (deflated 41%)
  adding: lib/liberty_buildpack/services/default.rb (deflated 71%)
  adding: lib/liberty_buildpack/services/mongo.rb (deflated 75%)
  adding: lib/liberty_buildpack/services/mysql.rb (deflated 68%)
  adding: lib/liberty_buildpack/services/postgresql.rb (deflated 67%)
  adding: lib/liberty_buildpack/services/relational_db.rb (deflated 76%)
  adding: lib/liberty_buildpack/services/utils.rb (deflated 74%)
  adding: lib/liberty_buildpack/services/vcap_services.rb (deflated 61%)
  adding: lib/liberty_buildpack/services.rb (deflated 40%)
  adding: lib/liberty_buildpack/util/ (stored 0%)
  adding: lib/liberty_buildpack/util/cache/ (stored 0%)
  adding: lib/liberty_buildpack/util/cache/admin_cache.rb (deflated 46%)
  adding: lib/liberty_buildpack/util/cache/application_cache.rb (deflated 49%)
  adding: lib/liberty_buildpack/util/cache/authentication_utils.rb (deflated 58%)
  adding: lib/liberty_buildpack/util/cache/cached_file.rb (deflated 70%)
  adding: lib/liberty_buildpack/util/cache/download_cache.rb (deflated 70%)
  adding: lib/liberty_buildpack/util/cache/inferred_network_failure.rb (deflated 41%)
  adding: lib/liberty_buildpack/util/cache/internet_availability.rb (deflated 61%)
  adding: lib/liberty_buildpack/util/cache.rb (deflated 40%)
  adding: lib/liberty_buildpack/util/configuration_utils.rb (deflated 70%)
  adding: lib/liberty_buildpack/util/constantize.rb (deflated 49%)
  adding: lib/liberty_buildpack/util/dash_case.rb (deflated 43%)
  adding: lib/liberty_buildpack/util/download.rb (deflated 65%)
  adding: lib/liberty_buildpack/util/format_duration.rb (deflated 54%)
  adding: lib/liberty_buildpack/util/heroku.rb (deflated 68%)
  adding: lib/liberty_buildpack/util/java_main_utils.rb (deflated 58%)
  adding: lib/liberty_buildpack/util/license_management.rb (deflated 49%)
  adding: lib/liberty_buildpack/util/location_resolver.rb (deflated 60%)
  adding: lib/liberty_buildpack/util/properties.rb (deflated 48%)
  adding: lib/liberty_buildpack/util/sanitizer.rb (deflated 42%)
  adding: lib/liberty_buildpack/util/service_configuration_utils.rb (deflated 66%)
  adding: lib/liberty_buildpack/util/tokenized_version.rb (deflated 64%)
  adding: lib/liberty_buildpack/util/to_b.rb (deflated 46%)
  adding: lib/liberty_buildpack/util/xml_utils.rb (deflated 63%)
  adding: lib/liberty_buildpack/util.rb (deflated 58%)
  adding: lib/liberty_buildpack.rb (deflated 40%)
  adding: LICENSE (deflated 65%)
  adding: NOTICE (deflated 6%)
  adding: README.md (deflated 61%)
  adding: resources/ (stored 0%)
  adding: resources/appdynamics_agent/ (stored 0%)
  adding: resources/appdynamics_agent/appdynamics.yml (deflated 65%)
  adding: resources/download_buildpack_cache.rb (deflated 67%)
  adding: resources/ibmjdk/ (stored 0%)
  adding: resources/ibmjdk/diagnostics/ (stored 0%)
  adding: resources/ibmjdk/diagnostics/killjava.sh (deflated 47%)
  adding: resources/liberty/ (stored 0%)
  adding: resources/liberty/create_vars.rb (deflated 60%)
  adding: resources/memory/ (stored 0%)
  adding: resources/memory/calculate_memory.rb (deflated 59%)
  adding: resources/memory/memory_bucket.rb (deflated 58%)
  adding: resources/memory/memory_limit.rb (deflated 47%)
  adding: resources/memory/memory_range.rb (deflated 65%)
  adding: resources/memory/memory_size.rb (deflated 65%)
  adding: resources/memory/openjdk_memory_heuristic_factory.rb (deflated 53%)
  adding: resources/memory/stack_memory_bucket.rb (deflated 50%)
  adding: resources/memory/weight_balancing_memory_heuristic.rb (deflated 69%)
  adding: resources/new_relic_agent/ (stored 0%)
  adding: resources/new_relic_agent/newrelic.yml (deflated 65%)
  adding: resources/openjdk/ (stored 0%)
  adding: resources/openjdk/diagnostics/ (stored 0%)
  adding: resources/openjdk/diagnostics/killjava.sh (deflated 48%)`

The zipped package is created. Once I add it to the PCF Dev buildpack list and push my application with the buildpack the following is shown and my application fails to stage:
`Staging app and tracing logs...
   Downloading ibm-websphere-liberty-buildpack...
   Downloaded ibm-websphere-liberty-buildpack
   Creating container
   Successfully created container
   Downloading app package...
   Downloaded app package (203.1M)
   Downloading build artifacts cache...
   Downloaded build artifacts cache (192.8M)
   Staging...
   Failed to read buildpack directory '/tmp/buildpacks/b90fb3740970db437a4c9f394e2bd513' for buildpack '10951062-4ee1-4254-bc44-bae1913b7c22_a6276480d75f1536265f5a9371f214f9a25e890784e42b6298cbea6a9ba668b6'
   None of the buildpacks detected a compatible application
   Exit status 222
   Staging failed: Exited with status 222
   Destroying container
   Successfully destroyed container
Error staging application: An app was not successfully detected by any available buildpack `

I'm unable to understand what is wrong through the logs and I would appreciate some help. Thanks!

**Comment by kevin-ortega** [comment]
Please reopen if still an issue.
