### ISSUE TITLE
Cache out of space : Failed to compress build artifacts: signal: broken pipe

### ISSUE THREAD

**Issue by dawu415** [cloudfoundry/ibm-websphere-liberty-buildpack#379]
When pushing an application to cloud foundry, the buildpack goes and downloads the JDK and IBM JRE components.  On a re-push, it re-downloads it, even though those components are already in cache.    What then happens is that the capacity of the cache runs out gives a `Failed to compress build artifacts: signal: broken pipe`.

To resolve this temporarily, we tested doing a rm -rf on the cache directory in the compile scripts and this fixes the problem.    The real fix probably should check the cache for the component first before redownloading.

**Comment by SilverFox70** [comment]
I am having a very similar problem myself. Sometimes the build works, and sometimes it does not. Removing the cache directory does not seem to ensure that the build will work, although maybe that is because I am not doing rm -rf on the correct location.

**Comment by kevin-ortega** [comment]
please reopen if still an issue.
