### ISSUE TITLE
Buildpack-enabled Options sessionDatabase not storing sessions

### ISSUE THREAD

**Issue by asureshkumaran** [cloudfoundry/ibm-websphere-liberty-buildpack#388]
We setup sessionDatabase on PCF.  It creates a table sessions with 11 columns.   We  restarted the sever (application) and refresh the page.  The session Doesn't appear.  noted all 3 blob columns are NULL.

Here is our settings in server.xml

<feature>sessionDatabase-1.0</feature>

    <library id="MySQLLib">
        
        
        <file name="${server.config.dir}/lib/mariadb-java-client-2.2.1.jar"/>
    </library>

        <jdbcDriver id="MySQLDriver"
                javax.sql.XADataSource='org.mariadb.jdbc.MariaDbDataSource'
                javax.sql.ConnectionPoolDataSource='org.mariadb.jdbc.MariaDbDataSource'
                libraryRef="MySQLLib"/>
    <dataSource id="SessionDS" jdbcDriverRef="MySQLDriver" transactional='true' type='javax.sql.XADataSource'>
       
        <properties
                databaseName="${cloud.services.perls-session-db.connection.name}"
                user="${cloud.services.perls-session-db.connection.user}"
                password="${cloud.services.perls-session-db.connection.password}"
                portNumber="${cloud.services.perls-session-db.connection.port}"
                serverName="${cloud.services.perls-session-db.connection.host}"
        />
    </dataSource>

    <httpSessionDatabase id="SessionDB" dataSourceRef="SessionDS"/>
    <httpSession storageRef="SessionDB" cloneId="${host}"/>

While deploying the app, we got the following warning 

   W, [2018-05-16T21:20:07.533516 #19]  WARN -- /tmp/buildpacks/8f5400416657d74dfdddb4414817d191/lib/liberty_buildpack/container/services_manager.rb:144:in `rescue in block in update_configuration': Failed to update the configuration for a service. Details are  The datasource configuration for service perls-session-db is inconsistent

**Comment by Algo21b** [comment]
If i solve the problem is there any money for that...
