### ISSUE TITLE
No D/N code found in the license file

### ISSUE THREAD

**Issue by FrigoCoder** [cloudfoundry/ibm-websphere-liberty-buildpack#391]
Hi!

Something changed between 2018-06-14 19:53 and 2018-06-15 11:12 (Central European Time). Deployment jobs started failing with the error message "No D/N code found in the license file". I updated the IBM_LIBERTY_LICENSE string to the newest, yet the error still occurrs.

An example log from a deployment build:

11:12:37 Staging app and tracing logs...
11:12:41    Successfully created container
11:12:41    Downloading app package...
11:12:42    Downloaded app package (3.9M)
11:12:42    Downloading build artifacts cache...
11:12:53    Downloaded build artifacts cache (253.2M)
11:12:53    Staging...
11:12:57    -----> Liberty Buildpack Version: 9369c92 | https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack.git#9369c92
11:12:58    E, [2018-06-15T11:12:55.830589 #56] ERROR -- /tmp/buildpacks/ea4b04e5e827cd41c0b5ee13910b4c8b/lib/liberty_buildpack/buildpack.rb:50:in `rescue in drive_buildpack_with_logger': Compile failed with exception #<RuntimeError: No D/N code found in the license file>
11:12:58    No D/N code found in the license file
11:12:58    Failed to compile droplet
11:12:58    Exit status 223
11:12:58    Staging failed: Exited with status 223
11:12:58    Destroying container
11:13:01    Successfully destroyed container
11:13:01 Error staging application: App staging failed in the buildpack compile phase

Br,
Frigo

**Comment by nvengatesan** [comment]
I have updated IBM_LIBERTY_LICENSE string to latest value and still, I am not able to deploy my application due to the below error. Can you please check error?


   2018-06-18T12:58:16.04+0530 [STG/0] OUT -----> Liberty Buildpack Version: 0e8db14 | https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack#0e8db14
   2018-06-18T12:58:16.49+0530 [STG/0] ERR E, [2018-06-18T07:28:16.489640 #56] ERROR -- /tmp/buildpacks/3df2de61de5a64348b4cb898aab001ae/lib/liberty_buildpack/buildpack.rb:50:in `rescue in drive_buildpack_with_logger': Compile failed with exception #<RuntimeError: No D/N code found in the license file>
   2018-06-18T12:58:16.49+0530 [STG/0] ERR No D/N code found in the license file
   2018-06-18T12:58:16.49+0530 [STG/0] ERR Failed to compile droplet
   2018-06-18T12:58:16.49+0530 [STG/0] OUT Exit status 223
   2018-06-18T12:58:16.52+0530 [STG/0] ERR Staging failed: Exited with status 223
   2018-06-18T12:58:16.53+0530 [STG/0] OUT Destroying container
   2018-06-18T12:58:16.57+0530 [API/0] ERR Failed to stage application: staging failed
   2018-06-18T12:58:17.49+0530 [STG/0] OUT Successfully destroyed container

**Comment by hmousaiti** [comment]
I am facing the same issue as well !!!

**Comment by hmousaiti** [comment]
I am facing the same issue as well !!!

**Comment by gytenisx** [comment]
We are also experiencing the same issue. Please help!

**Comment by gytenisx** [comment]
Tried all D/N codes from this link but none seem to work:

http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/index.yml

**Comment by gytenisx** [comment]
Please check license download code from download_buildpack_cache.rb (see below). It could be it tried to find yaml value by version key which doesn't exist in index.yaml file:

```
def download_cache(configs)
    if configs.empty?
      @logger.warn 'No cache to download.'
      return
    end

    FileUtils.mkdir_p(@cache_dir)

    configs.each do |config|
      # Download index.yml first.
      index_uri = index_path(config)
      index_file = File.join(@cache_dir, filename(index_uri))
      download(index_uri, index_file)
      # Parse index.yml to see what files it references
      begin
        index = YAML.load_file(index_file)
      rescue => e
        abort "ERROR: Failed loading #{index_uri}: #{e}"
      end
      candidate = LibertyBuildpack::Util::TokenizedVersion.new(config[VERSION])
      version = LibertyBuildpack::Repository::VersionResolver.resolve(candidate, index.keys)
      if version.nil?
        @logger.warn "No matches found for #{candidate} version in #{index_uri}."
        next
      end
      file_uri = download_license(index[version.to_s], config[TYPE_KEY])
      file = File.join(@cache_dir, filename(file_uri))
      download(file_uri, file)
      # If file is a component_index.yml parse and download files it references as well
      download_components(file_uri, file) if file_uri.end_with? COMP_INDEX_PATH
    end
  end
```

**Comment by gytenisx** [comment]
So, there's "18.0.0_01" version in the main license config file:
http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/index.yml

But there's no path with version "18.0.0_01", only "18.0.0.1" here:
https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/

So, my assumption would someone made a typo and the key should be changed from "18.0.0_01" to "18.0.0.1" in main license config file:
http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/index.yml

**Comment by kevin-ortega** [comment]
I am working with the Liberty team to change the index.yml file.

**Comment by kevin-ortega** [comment]
The issue is not with the Liberty license. The issue is with the JVM license.   You can work around this issue by using the open jdk by setting the JVM environment variable:  

     cf set-env myapp JVM 'openjdk'

We are continuing to investigate why the license issue exists with the default JRE.

**Comment by MFranca** [comment]
I am still facing this issue... :-(

**Comment by AhmedAbdelMaksoud** [comment]
This issue is happening again this weekend

**Comment by kevin-ortega** [comment]
@AhmedAbdelMaksoud Thanks for reporting this issue.   Java 8.0.6.11 was released on Friday and it appears the Java team hasn't updated a license file.   For now as a work around you can specify Java 8.0.6.10 with:

`cf set-env myApp JBP_CONFIG_IBMJDK 'version: 1.8.0_sr6fp10'

**Comment by AhmedAbdelMaksoud** [comment]
Thank you so much Kevin for the quick reply. This worked great.
Just a tiny correction to the command for anyone looking at it later: 
cf set-env myApp JBP_CONFIG_IBMJDK "version: 1.8.0_sr6fp10"

**Comment by kevin-ortega** [comment]
@AhmedAbdelMaksoud This issue is has been fixed with liberty.  You can remove work around.

**Comment by AhmedAbdelMaksoud** [comment]
Thanks Kevin, yes it is working normally now.
