### ISSUE TITLE
Support for non-Bluemix Cloud Foundries?

### ISSUE THREAD

**Issue by pburkholder** [cloudfoundry/ibm-websphere-liberty-buildpack#397]
Hi,

Back in #378 you accepted support for this buildpack on cloud.gov.

But then #381 reverted that.

Do you have another mechanism for supporting this buildpack that doesn't rely on the naming conventions of BlueMix?

Thanks, Peter

**Comment by kevin-ortega** [comment]
Hi, yes I did merge your PR but it was causing some test failures down the pipeline.   I didn't have time to figure out the failure so I had to revert it.   We can try again.
