### ISSUE TITLE
calculate_memory does not consider commented lines

### ISSUE THREAD

**Issue by smikishk** [cloudfoundry/ibm-websphere-liberty-buildpack#405]
resource: resource/memory/calculate_memory.rb
methods:  set_openjdk_config | set_openjdk_config
code: File.readlines(java_opts_file).grep(/-Xmx/).size > 0

In Eclipse IDE, there is an option to generate jvm.options file for the first time.  It comes blank, but has usage suggestions as comments:

\# Uncomment the following line to set the maximum heap size to 1024m
\#-Xmx1024m

The buildpack logic does not consider commented out lines and thus assumes the user has set -Xmx instead of calculating memory.

Commented out line(s) should not be considered as part of the server configuration.

**Comment by jgawor** [comment]
Fixed in #408.
