### ISSUE TITLE
Update New Relic Agent

### ISSUE THREAD

**Issue by wfc-sfmjp** [cloudfoundry/ibm-websphere-liberty-buildpack#411]
In the past two weeks, New Relic Java APM began reporting inaccurate response times for requests. After deploying a fresh application with ibm-websphere-liberty-buildpack, the following New Relic Agent is used:

![image](https://user-images.githubusercontent.com/38355180/50241483-9701d180-0395-11e9-8e28-863d8d89361b.png)

New Relics current release is [4.9.0](http://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/), which is a major version ahead. Following [java-buildpack's](https://github.com/cloudfoundry/java-buildpack/blob/master/config/new_relic_agent.yml) lead, we should update the new_relic_agent.yml to use 4.+. I have patched it on a [fork](https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack/compare/master...wakefern:master). Let me know what else is required!

**Comment by wfc-sfmjp** [comment]
Any contributors able to assist issuing the pull request?

**Comment by kevin-ortega** [comment]
I'll update the yml.

**Comment by wfc-sfmjp** [comment]
Thanks @kevin-ortega!

**Comment by kevin-ortega** [comment]
@wfc-sfmjp Done.
