### ISSUE TITLE
Looking for possibility to fetch versions selected by VersionResolver

### ISSUE THREAD

**Issue by krismarc** [cloudfoundry/ibm-websphere-liberty-buildpack#473]
Dear community,

we are using this buildpack to deploy over 3k+ company internal applications using various WLP and java versions (numbers are still growing). Problem appears when it comes to turn off outdated version in the registry which could be still potentially used by some applications. 

We would like to have an option to see all versions currently used by our workload or have an option to build up our own registry/database with exact versions used and stored there.
Currently the only place where we could fetch versions selected by the buildpack resolver is the log file generated during application deployment. 

```
-----> Downloading IBM 1.8.0_sr6fp1101 JRE from http://wls-java-8-0-6-11-01.***/linux/sr-ibm-java-jre-8.0.6.11_01-linux.tar.gz ... (1.3s)
         Expanding JRE to .java ... (1.9s)
-----> Downloading from http://wls-20-0-0-7_01.***/sr-wlp-base-javaee-all-20.0.0.7_01.zip ... (2.5s)
         Installing archive ... (2.7s)
```

This metadata isn't present anywhere within Cloud Foundry API and I couldn't find any other way than:
1. own buildpack customization to expose/export values - which might be problematic when it comes to the upgrade
2. building up own resolver based on the same logic as you do in buildpack code - extra code to be maintained (the wildcard "+" is the most problematic and breaking point in this idea)
3. parsing the log file to get the data - the nature of this solution is bad but comes into a game due to lack of other possibilities

We would really appreciate if you could check on this and consider providing such a feature. Having values exportable from the buildpack would be fair enough. Having it stored within CF or as a part of workload definition would be additional valuable option.

Kind regards,
K.M.

**Comment by kevin-ortega** [comment]
@KrzMar This is an interesting request.  I do see some merit in such a feature but I'm not aware of any method for the buildpack to add metadata so it would be available via a CF API.   

The information you are looking for is available on the app's filesystem and can be obtained using CF CLI.  

The header of Liberty's message.log shows the liberty and java versions: 

```
$ cf ssh <appname> -c "head -10 logs/messages.log"
********************************************************************************
product = WebSphere Application Server 20.0.0.6 (wlp-1.0.41.cl200620200528-0414)
wlp.install.dir = /home/vcap/app/.liberty/
server.config.dir = /home/vcap/app/wlp/usr/servers/defaultServer/
java.home = /home/vcap/app/.java/jre
java.version = 1.8.0_251
java.runtime = Java(TM) SE Runtime Environment (8.0.6.10 - pxa6480sr6fp10-20200408_01(SR6 FP10) Small Footprint)
os = Linux (4.15.0-112-generic; amd64) (en_US)
process = 102@10.246.15.159
********************************************************************************
```

Alternatively, the staging log is also available on the file system.  

```
$ cf ssh <appname> -c "cat app/logs/staging_task.log"
-----> Liberty Buildpack Version: v20200528-1800
-----> Retrieving IBM 1.8.0_sr6fp10-20200408 JRE (ibm-java-jre-8.0-6.10-pxa6480sr6fp10-20200408_01-cloud.tgz) ... (0.0s)
         Expanding JRE to .java ... (1.6s)
-----> Retrieving App Management 1.29.0_20200406-1609 (app-mgmt_v1.29-20200406-1609.zip) ... (0.0s)
         Expanding App Management to .app-management (0.1s)
-----> Retrieving com.ibm.ws.liberty-20.0.0.6-202005281800.tar.gz ... (0.0s)
         Installing archive ... (1.0s)
-----> Retrieving com.ibm.ws.liberty.ext-20.0.0.6-202005281800.tar.gz ... (0.0s)
         Installing archive ... (1.7s)
-----> Retrieving com.ibm.ws.liberty.javaee7-20.0.0.6-202005281800.tar.gz ... (0.0s)
         Installing archive ... (1.7s)
-----> Retrieving and installing client jar(s) from com.ibm.ws.icap.clientJars.cloudant.zip (0.0s)
-----> Warning: Liberty feature set is not specified. Using the default feature set: ["beanValidation-1.1", "cdi-1.2", "ejbLite-3.2", "el-3.0", "jaxrs-2.0", "jdbc-4.1", "jndi-1.0", "jpa-2.1", "jsf-2.2", "jsonp-1.0", "jsp-2.3", "managedBeans-1.0", "servlet-3.1", "websocket-1.1"]. For the best results, explicitly set the features via the JBP_CONFIG_LIBERTY environment variable or deploy the application as a server directory or packaged server with a custom server.xml file.
-----> Auto-configuration is creating config for service instance 'myCloudant' of type 
```
I realize both of these methods require parsing of a log file but with scripting it can be easily accomplished and not rely on the availability of the log when the app is pushed.

**Comment by KrzMar** [comment]
Hi @kevin-ortega, thank you for the answer

we also had this assumption that there's no option to manipulate with CF API while staging. One of sentences in CF documentation made me feeling it could be somehow possible. 
https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html

"You can access environment variables programmatically, including variables defined by the buildpack. For more information, see the buildpack documentation for Java, Node.js, and Ruby."

-------------

Anyway, is that for any reason intentional you don't print **liberty_version** as you do with **java_version** (right after "_-----> Downloading_" string)?

> 
> -----> Downloading IBM **1.8.0_sr6fp1101** JRE from http://wls-java-8-0-6-11-01.***/linux/sr-ibm-java-jre-8.0.6.11_01-linux.tar.gz ... (1.3s)
>          Expanding JRE to .java ... (1.9s)
> -----> Downloading **<-here we miss it->** from http://wls-20-0-0-7_01.***/sr-wlp-base-javaee-all-20.0.0.7_01.zip ... (2.5s)
>          Installing archive ... (2.7s)
> 

-------------

https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack/blob/a4cf092abd8ef18f1ce81a6e658049986b2b6fd3/lib/liberty_buildpack/jre/ibmjdk.rb#L74
```
    def compile
      @version, @uri, @license = IBMJdk.find_ibmjdk(@configuration)
      .
      .
      ibm_var = ' IBM'
      download_start_time = Time.now
      if @uri.include? '://'
        print "-----> Downloading#{ibm_var} #{@version} JRE from #{@uri} ... "
      else
      .
      .
        ibm_var = '' if filename.include? 'open'
        print "-----> Retrieving#{ibm_var} #{@version} JRE (#{filename}) ... "
      end
```

https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack/blob/a4cf092abd8ef18f1ce81a6e658049986b2b6fd3/lib/liberty_buildpack/container/liberty.rb#L708
```
    def download_and_unpack_archive(uri, root)
      # all file types filtered here should be handled inside block.
      if uri.end_with?('.tgz', '.tar.gz', '.zip', 'jar')
        if uri.include? '://'
          print "-----> Downloading from #{uri} ... "
        else
          filename = File.basename(uri)
          print "-----> Retrieving #{filename} ... "
        end
```

However, by adding one function call to the last snippet we could also get liberty version as well:
`liberty_version = Liberty.find_liberty_item(@app_dir, @configuration)[0]`

..and by using variable in the right place eg:
`print "-----> Downloading liberty #{liberty_version} from #{uri} ... "`

it would give as expected output in the staging log file. (or we could add extra line telling which version is selected by the resolver - to not break scripts people might already have)

If that's just overlooked thing. I would be glad to place a proper pull request. WDYT?

Best regards,
K.M.

**Comment by KrzMar** [comment]
Seems like such a function is already there in newer versions of buildpack. eg in the one you use in public cloud..

```
vcap@45be20a4-9a34-4834-4e75-1c36:~$ cat ~/staging_info.yml
{"detected_buildpack":"Liberty for Java(TM) (WAR, liberty-20.0.0_9, buildpack-v3.49-20200918-0244, ibmjdk-1.8.0_sr6fp15-20200724, env)","start_command":".liberty/initial_startup.rb"}
```
```
vcap@45be20a4-9a34-4834-4e75-1c36:~$ cat app/logs/staging_task.log
Liberty for Java(TM) (WAR, liberty-20.0.0_9, buildpack-v3.49-20200918-0244, ibmjdk-1.8.0_sr6fp15-20200724, env)
-----> Liberty Buildpack Version: v3.49-20200918-0244
-----> Retrieving IBM 1.8.0_sr6fp15-20200724 JRE (ibm-java-jre-8.0-6.15-pxa6480sr6fp15-20200724_01-cloud-unrestricted.tgz) ... (0.0s)
         Expanding JRE to .java ... (1.8s)
-----> Retrieving App Management 1.29.0_20200406-1609 (app-mgmt_v1.29-20200406-1609.zip) ... (0.0s)
         Expanding App Management to .app-management (0.1s)
-----> Retrieving com.ibm.ws.liberty-20.0.0.9-202009180244.tar.gz ... (0.0s)
         Installing archive ... (1.7s)
-----> Retrieving com.ibm.ws.liberty.ext-20.0.0.9-202009180244.tar.gz ... (0.0s)
         Installing archive ... (2.3s)
-----> Retrieving com.ibm.ws.liberty.javaee7-20.0.0.9-202009180244.tar.gz ... (0.0s)
         Installing archive ... (4.7s)
-----> Retrieving and installing client jar(s) from com.ibm.ws.icap.clientJars.cloudant.zip (0.1s)
-----> Warning: Liberty feature set is not specified. Using the default feature set: ["beanValidation-1.1", "cdi-1.2", "ejbLite-3.2", "el-3.0", "jaxrs-2.0", "jdbc-4.1", "jndi-1.0", "jpa-2.1", "jsf-2.2", "jsonp-1.0", "jsp-2.3", "managedBeans-1.0", "servlet-3.1", "websocket-1.1"]. For the best results, explicitly set the features via the JBP_CONFIG_LIBERTY environment variable or deploy the application as a server directory or packaged server with a custom server.xml file.
-----> Auto-configuration is creating config for service instance 'cloudantNoSQLDB' of type 'cloudantNoSQLDB'
-----> Liberty buildpack is done creating the droplet
```

**Comment by kevin-ortega** [comment]
@krismarc Can you reach out to me on Slack or email (ortegake@us.ibm.com)?
