### ISSUE TITLE
Compression feature

### ISSUE THREAD

**Issue by KrzMar** [cloudfoundry/ibm-websphere-liberty-buildpack#480]
Dear Liberty Buildpack Contributors/Community,

recently, you have added a feature which enables compression by default. However, it seems to be not conditionally handled and an extra empty <compression/> tag is being added, even if it's already specified. This leads in override of parameters specified by the user in his server.xml and compression is not working as it's expected. 

Shouldn't this be skipped if compression is already specified and present in provided server.xml?

My Ruby knowledge is low. However, this part seems to be clear (it's not a part of any IF statement):
https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack/blob/7c2643dccfbdfb663bbfb0c996dc9048baa9f553/lib/liberty_buildpack/container/liberty.rb#L476

User provided part:
```
    <httpEndpoint id="defaultHttpEndpoint" host="*" httpPort="${port}">
        <!-- Enable response compression -->
        <compression serverPreferredAlgorithm="gzip">
            <types>+application/json</types>
            <types>-text/plain</types>
        </compression>
    </httpEndpoint>
```
![good](https://user-images.githubusercontent.com/38418755/101479120-f5913300-3951-11eb-8b02-8c032d2e2a1b.png)

Results after staging:
```
    <httpEndpoint id="defaultHttpEndpoint" host="*" httpPort="${port}">
        <!-- Enable response compression -->
        <compression serverPreferredAlgorithm="gzip">
            <types>+application/json</types>
            <types>-text/plain</types>
        </compression>
        <compression/>
    </httpEndpoint>
```
![bad](https://user-images.githubusercontent.com/38418755/101479122-f6c26000-3951-11eb-93f3-1fff35905a4a.png)

Server xmls compared after staging against BP v3.20 and v3.16:
![staging_compare](https://user-images.githubusercontent.com/38418755/101479559-ab5c8180-3952-11eb-8799-e09ad58e5000.png)

Best regards,
K.M.

**Comment by preetisawant** [comment]
Hello @KrzMar, 

The issue has been fixed. Please reopen the issue if you encounter otherwise.

Thanks!

**Comment by KrzMar** [comment]
Hi @preetisawant @kevin-ortega,

there's a typo in "compression" word.
https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack/pull/483/files.

Please change it before your release?

Best regards,
K.M.
