### ISSUE TITLE
Does the buildpack support .profile execution

### ISSUE THREAD

**Issue by berndgoetz** [cloudfoundry/ibm-websphere-liberty-buildpack#482]
The Java buildpack supports the execution of shell commands before the application start. It works in the way that adding a .profile file leads to the execution of it. The file is to be put into the root of an executable jar (tried this, ti works) or to the root of a war file (didn't try this). 

Does the IBM Websphere Liberty buildpack support this?

**Comment by kevin-ortega** [comment]
@berndgoetz execution of .profile or .profile.d is really a function of CF.  But, they can be used when using the liberty buildpack.  They need to be in the app root directory.   For example, I have a directory structure like this:

~/mydir
~/mydir/app/
~/mydir/app/myapp.war
~/mydir/.profile
~/mydir/server.xml

cf push MyAppName -p ~/mydir
