### ISSUE TITLE
Compression feature - reopen

### ISSUE THREAD

**Issue by KrzMar** [cloudfoundry/ibm-websphere-liberty-buildpack#484]
Hi @preetisawant @kevin-ortega,

I can't reopen an issue closed by one of collaborators.

There's a typo in "compression" word.
https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack/pull/483/files.

Please change it before your release?

Best regards,
K.M.

**Comment by KrzMar** [comment]
Ok, I see. You have made 2 more commits directly to master after merging your recent PR.
https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack/commit/e282d02d407d7225fca4ca3756d2aa2a4749be7d
https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack/commit/6c04cb1b363179c96a9be7d4edf07b2401b8e995

**Comment by preetisawant** [comment]
Fixed. Thanks!
