### ISSUE TITLE
running behind a firewall

### ISSUE THREAD

**Issue by tomaszkosturek** [cloudfoundry/ibm-websphere-liberty-buildpack#55]
Hi,
I'm struggling with getting the liberty buildpack fully functional within our intranet. I have followed the instructions in docs/util-repositories.md, the jre and wlp runtime are getting downloaded from my internal repo, but the deployments are still failing when trying to find the wlp features listed in the server.xml:

-----> Downloaded app package (4.7M)
-----> Downloading IBM 1.7.0 JRE from http://chrav012.swissre.com/images/Pivotal_Software/buildpacks/ibm/jre/ibm-java-jre-7.0-5.0-x86_64-archive.bin (1.0s)
       Expanding JRE to .java (15.2s)
Downloading from http://chrav012.swissre.com/images/Pivotal_Software/buildpacks/ibm/wlp/8.5.5.2/wlp-developers-runtime-8.5.5.2.jar ... (0.5s).
Installing archive ... (1.0s).
E, [2014-05-15T12:47:25.359915 #50] ERROR -- /var/vcap/data/dea_next/admin_buildpacks/7f537c32-ec1e-4da1-833f-8e42bb338995_fd5a4d6e0fd8b9c9fca559aae7f904e567f9b41d/lib/liberty_buildpack/buildpack.rb:46:in `rescue in drive_buildpack_with_logger': Compile failed with exception #<RuntimeError: could not install required features, output is CWWKF1203E: Unable to obtain the following features: [webProfile-6.0]
>
could not install required features, output is CWWKF1203E: Unable to obtain the following features: [webProfile-6.0]
/var/vcap/packages/dea_next/buildpacks/lib/installer.rb:19:in `compile': Buildpack compilation step failed: (RuntimeError)
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:74:in `block in compile_with_timeout'
        from /usr/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:73:in `compile_with_timeout'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:54:in `block in stage_application'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:50:in `chdir'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:50:in `stage_application'
        from /var/vcap/packages/dea_next/buildpacks/bin/run:10:in `<main>'

FAILED
Server error, status code: 400, error code: 170001, message: Staging error: cannot get instances since staging failed

**Comment by jgawor** [comment]
Closing this as:
1. HTTP_PROXY and HTTPS_PROXY environment variables are supported now.
2. Provided better documentation on [configuring Liberty repository information](https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack/blob/master/docs/container-liberty.md#liberty-repository-configuration).
