### ISSUE TITLE
cflinuxfs4 support

### ISSUE THREAD

**Issue by krismarc** [cloudfoundry/ibm-websphere-liberty-buildpack#555]
Dear @kevin-ortega and all other contributors,

by any chance, do you know if current version of the buildpack will be compatible with cflinuxfs4?
Other buildpacks are getting prepared. Not sure what's the effort (if any) to get this done for Liberty one. (if I am not mistaken, there were no changes required for the move from cflinuxfs2 to cflinuxfs3)
eg. https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.52

Unfortunately, due to my access limitations I can't perform any tests until the new stack is available in our environment (not in my scope). Would you be able to give it a try and share your feedback?

Best regards,
K.M.

**Comment by kevin-ortega** [comment]
I anticipate that the buildpack will run on cflinuxfs4 without any changes.  We did not make any modifications moving from cflinuxfs2 to cflinuxfs3.   

Unfortunately, I do not have access to a cflinuxfs4 environment and am not able to validate the buildpack will run.   It is not likely IBM Cloud will install cflinuxfs4 but that is only speculation on my part.  

While the buildpack itself was unmodified when cflinuxfs3 came out, there was one change I did have to make in the script used to build an admin buildpack.  

![image](https://user-images.githubusercontent.com/29545669/199719823-e608dcb4-29f2-436a-8cd0-ba00223cf8f8.png)

I suspect a similar change will need to be made to work with cflinuxfs4,  `bionic -> jammy`.

**Comment by kevin-ortega** [comment]
I did confirm with the CF folks, there are no plans to add cflinuxfs4

**Comment by krismarc** [comment]
@kevin-ortega, what's their problem? I'd understand having this pushed to become default stack. However, having it optional shouldn't be a pain for them? or just tell them to enable it in their lab/exp and don't even set it to default one. This should be enough for testing.

> I think I need to keep the hardcoded ubuntu version because building the buildpack can occur on any machine, not just ubuntu. I do all my development work on macos and lsb_release doesn't exist. I will likely cut a release that has bionic so people building for cflinuxfs2 can continue if/when I add support for cflinuxfs4.

Ok, I though it's just needed during execution/interpretation when buildpack is actually used within CF staging.
